project_id = "pjplcsuyhybwoinlwnnb"

[auth]
site_url = "https://ai.mobiwave.co.ke"
additional_redirect_urls = [
  "https://ai.mobiwave.co.ke",
  "https://ai.mobiwave.co.ke/reset-password"
]

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600

[functions.chat]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.get-contact-info]
verify_jwt = false

[functions.github-webhook]
verify_jwt = false

[functions.send-ticket-email]
verify_jwt = false

[functions.auto-create-ticket]
verify_jwt = false

[functions.widget-conversation]
verify_jwt = false
